import React from "react";
import { Calendar, List } from "lucide-react";

export type ReportSidebarProps = {
    generatedBy: string;
    setGeneratedBy: (val: string) => void;
    statusFilter: "all" | "active" | "inactive";
    setStatusFilter: (val: "all" | "active" | "inactive") => void;
    fromDate: string;
    setFromDate: (val: string) => void;
    toDate: string;
    setToDate: (val: string) => void;
    loadErr: string | null;
};

export function ReportSidebar({
    generatedBy,
    setGeneratedBy,
    statusFilter,
    setStatusFilter,
    fromDate,
    setFromDate,
    toDate,
    setToDate,
    loadErr,
}: ReportSidebarProps) {
    return (
        <aside className="w-[260px] shrink-0">
            <div className="bg-white border border-[#e2e8f0] rounded-[4px] p-[15px]">
                <div className="font-bold mb-5 pl-2.5 border-l-4 border-[#2b6cb0] uppercase text-[#2d3748] text-[13px]">
                    Filters
                </div>

                <div className="mb-[15px]">
                    <label className="block text-[11px] text-[#718096] mb-[5px] uppercase font-semibold">Forecast Date</label>
                    <div className="relative mb-[5px]">
                        <input
                            className="w-full px-2.5 py-2 border border-[#e2e8f0] rounded-[4px] text-[13px] text-[#2d3748] bg-white placeholder:text-[#a0aec0] focus:outline-none focus:border-[#2b6cb0] [color-scheme:light]"
                            type="date"
                            placeholder="From"
                            value={fromDate}
                            onChange={(e) => setFromDate(e.target.value)}
                        />
                    </div>
                    <div className="relative">
                        <input
                            className="w-full px-2.5 py-2 border border-[#e2e8f0] rounded-[4px] text-[13px] text-[#2d3748] bg-white placeholder:text-[#a0aec0] focus:outline-none focus:border-[#2b6cb0] [color-scheme:light]"
                            type="date"
                            placeholder="To"
                            value={toDate}
                            onChange={(e) => setToDate(e.target.value)}
                        />
                    </div>
                </div>

                <div className="mb-[15px]">
                    <label className="block text-[11px] text-[#718096] mb-[5px] uppercase font-semibold">Status</label>
                    <div className="relative">
                        <select
                            className="w-full px-2.5 py-2 border border-[#e2e8f0] rounded-[4px] text-[13px] text-[#2d3748] bg-white appearance-none cursor-pointer focus:outline-none focus:border-[#2b6cb0]"
                            value={statusFilter}
                            onChange={(e) => setStatusFilter(e.target.value as any)}
                        >
                            <option value="all">All</option>
                            <option value="active">Active</option>
                            <option value="inactive">Archived</option>
                        </select>
                        <div className="absolute inset-y-0 right-0 flex items-center px-2.5 pointer-events-none text-[#718096]">
                            <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
                        </div>
                    </div>
                </div>

                <div className="mb-[15px]">
                    <label className="block text-[11px] text-[#718096] mb-[5px] uppercase font-semibold">Generated By</label>
                    <div className="relative">
                        <select
                            className="w-full px-2.5 py-2 border border-[#e2e8f0] rounded-[4px] text-[13px] text-[#2d3748] bg-white appearance-none cursor-pointer focus:outline-none focus:border-[#2b6cb0]"
                            value={generatedBy}
                            onChange={(e) => setGeneratedBy(e.target.value)}
                        >
                            <option value="">All</option>
                            <option value="team">Team members</option>
                            <option value="system">System</option>
                        </select>
                        <div className="absolute inset-y-0 right-0 flex items-center px-2.5 pointer-events-none text-[#718096]">
                            <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
                        </div>
                    </div>
                </div>

                <button
                    className="w-full bg-[#2b6cb0] hover:bg-[#2c5282] text-white border-none p-2.5 rounded-[4px] font-semibold cursor-pointer mb-[10px] transition-colors text-[14px]"
                    onClick={() => { }}
                >
                    APPLY FILTERS
                </button>

                <button
                    className="w-full bg-white text-[#2d3748] border border-[#e2e8f0] hover:bg-slate-50 p-2 rounded-[4px] font-medium cursor-pointer flex items-center justify-center gap-2 transition-colors text-[14px]"
                    onClick={() => {
                        setGeneratedBy("");
                        setStatusFilter("all");
                        setFromDate("");
                        setToDate("");
                    }}
                >
                    <List className="h-3.5 w-3.5" />
                    RESET
                </button>

                {loadErr ? (
                    <div className="mt-3 p-2 bg-red-50 border border-red-100 text-red-600 font-bold text-xs rounded">
                        {loadErr}
                    </div>
                ) : null}
            </div>
        </aside>
    );
}
